### ISSUE TITLE
"'" makes the rest of the file incorrectly highlighted

### ISSUE THREAD

**Issue by ksqsf** [nishtahir/language-kotlin#51] opened 2021-04-05 09:32 UTC
For example,

<img width="604" alt="截屏2021-04-05 17 31 36" src="https://user-images.githubusercontent.com/23358293/113559944-c905d300-9634-11eb-8916-e901af660bed.png">

**Comment by nishtahir** [comment] 2021-04-05 14:04
Duplicate of #49

**Closed by nishtahir** 2021-04-05 14:04 UTC
